/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package team2;

/**
 *
 * @author Nabila
 */
public class dataTeam2 extends javax.swing.JFrame {

    /**
     * Creates new form dataTeam2
     */
    public dataTeam2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLatar = new javax.swing.JPanel();
        lKel = new javax.swing.JLabel();
        lidentitasAnggota = new javax.swing.JLabel();
        bNabila = new javax.swing.JButton();
        bAni = new javax.swing.JButton();
        bAngga = new javax.swing.JButton();
        lSem3 = new javax.swing.JLabel();
        bAhid = new javax.swing.JButton();
        bIlham = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pLatar.setBackground(new java.awt.Color(204, 255, 255));

        lKel.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lKel.setText("Kelompok II Sistem Informasi");

        lidentitasAnggota.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lidentitasAnggota.setText("Identidas Anggota");

        bNabila.setBackground(new java.awt.Color(153, 204, 255));
        bNabila.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        bNabila.setText("Nabila Putri Ardina");
        bNabila.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bAni.setBackground(new java.awt.Color(153, 204, 255));
        bAni.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        bAni.setText("Siti Novi Triani");
        bAni.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bAni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAniActionPerformed(evt);
            }
        });

        bAngga.setBackground(new java.awt.Color(153, 204, 255));
        bAngga.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        bAngga.setText("Angga Sanjaya");
        bAngga.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lSem3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lSem3.setText("Semester III");

        bAhid.setBackground(new java.awt.Color(153, 204, 255));
        bAhid.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        bAhid.setText("Muhammad Armiya Ahid");
        bAhid.setActionCommand("");
        bAhid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bAhid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAhidActionPerformed(evt);
            }
        });

        bIlham.setBackground(new java.awt.Color(153, 204, 255));
        bIlham.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        bIlham.setText("Muhammad Ilham Muzaqi");
        bIlham.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bIlham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIlhamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pLatarLayout = new javax.swing.GroupLayout(pLatar);
        pLatar.setLayout(pLatarLayout);
        pLatarLayout.setHorizontalGroup(
            pLatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLatarLayout.createSequentialGroup()
                .addGroup(pLatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pLatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pLatarLayout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addComponent(lidentitasAnggota))
                        .addGroup(pLatarLayout.createSequentialGroup()
                            .addGap(77, 77, 77)
                            .addComponent(lKel)))
                    .addGroup(pLatarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pLatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bIlham, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bAhid, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bAngga, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bAni, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bNabila, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pLatarLayout.createSequentialGroup()
                                .addComponent(lSem3)
                                .addGap(80, 80, 80)))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        pLatarLayout.setVerticalGroup(
            pLatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLatarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lidentitasAnggota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lKel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lSem3)
                .addGap(31, 31, 31)
                .addComponent(bNabila, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bAni, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bAngga, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bAhid, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bIlham, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pLatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pLatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bAniActionPerformed

    private void bAhidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAhidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bAhidActionPerformed

    private void bIlhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIlhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bIlhamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataTeam2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataTeam2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataTeam2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataTeam2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataTeam2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAhid;
    private javax.swing.JButton bAngga;
    private javax.swing.JButton bAni;
    private javax.swing.JButton bIlham;
    private javax.swing.JButton bNabila;
    private javax.swing.JLabel lKel;
    private javax.swing.JLabel lSem3;
    private javax.swing.JLabel lidentitasAnggota;
    private javax.swing.JPanel pLatar;
    // End of variables declaration//GEN-END:variables
}
