/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package team2;

/**
 *
 * @author Nabila
 */
public class Nabila extends javax.swing.JFrame {

    /**
     * Creates new form Nabila
     */
    public Nabila() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        lFoto = new javax.swing.JLabel();
        lNIM = new javax.swing.JLabel();
        lNama = new javax.swing.JLabel();
        lIdentitasDiri = new javax.swing.JLabel();
        lAlamat = new javax.swing.JLabel();
        lLinkGithub = new javax.swing.JLabel();
        lProdi = new javax.swing.JLabel();
        lKel = new javax.swing.JLabel();
        lAngkatan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        lFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team2/Nabila.png"))); // NOI18N
        lFoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lFoto.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(lFoto);
        lFoto.setBounds(320, 70, 160, 194);

        lNIM.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lNIM.setText("NIM      :    202457201055");
        jPanel1.add(lNIM);
        lNIM.setBounds(16, 99, 212, 17);

        lNama.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lNama.setText("Nama   :    Nabila Putri Ardina");
        jPanel1.add(lNama);
        lNama.setBounds(16, 70, 220, 17);

        lIdentitasDiri.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        lIdentitasDiri.setText("IDENTITAS DIRI");
        jPanel1.add(lIdentitasDiri);
        lIdentitasDiri.setBounds(185, 20, 150, 22);

        lAlamat.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lAlamat.setText("Alamat :    Sukorejo, Loceret, Nganjuk");
        jPanel1.add(lAlamat);
        lAlamat.setBounds(16, 128, 286, 17);

        lLinkGithub.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lLinkGithub.setText("Link Github : https://github.com/Biyabylla/firstCollabTeam2.git");
        jPanel1.add(lLinkGithub);
        lLinkGithub.setBounds(16, 282, 480, 17);

        lProdi.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lProdi.setText("Program Studi : Sistem Informasi");
        jPanel1.add(lProdi);
        lProdi.setBounds(16, 157, 286, 17);

        lKel.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lKel.setText("Kelompok : II");
        jPanel1.add(lKel);
        lKel.setBounds(16, 203, 286, 17);

        lAngkatan.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lAngkatan.setText("Angkatan : 2024");
        jPanel1.add(lAngkatan);
        lAngkatan.setBounds(16, 180, 286, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team2/background.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 520, 370);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 520, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nabila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nabila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nabila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nabila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nabila().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lAlamat;
    private javax.swing.JLabel lAngkatan;
    private javax.swing.JLabel lFoto;
    private javax.swing.JLabel lIdentitasDiri;
    private javax.swing.JLabel lKel;
    private javax.swing.JLabel lLinkGithub;
    private javax.swing.JLabel lNIM;
    private javax.swing.JLabel lNama;
    private javax.swing.JLabel lProdi;
    // End of variables declaration//GEN-END:variables
}
